const FILTER_CATEGORIES = ["Clothing", "Decoration", "Gift", "Caps", "Sweater"];
const RATING_FILTER = "RATING_FILTER";
const CATEGORY_FILTER = "CATEGORY_FILTER";
const PRICE_FILTER = "PRICE_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";
const SORT_PRICE_ASC_FILTER = "SORT_PRICE_ASC_FILTER";
const UPDATE_USER_DATA = "UPDATE_USER_DATA";
const UPDATE_TOKEN_AND_DATA = "UPDATE_TOKEN_AND_DATA";
const CREDENTIAL_CHECK = "CREDENTIAL_CHECK";
const USER_NOT_FOUND = "USER_NOT_FOUND";
export {
  FILTER_CATEGORIES,
  RATING_FILTER,
  CATEGORY_FILTER,
  PRICE_FILTER,
  CLEAR_FILTER,
  SORT_PRICE_ASC_FILTER,
  UPDATE_USER_DATA,
  UPDATE_TOKEN_AND_DATA,
  CREDENTIAL_CHECK,
  USER_NOT_FOUND,
};
