const FILTER_CATEGORIES = ["Clothing", "Decoration", "Gift", "Caps", "Sweater"];
const RATING_FILTER = "RATING_FILTER";
const CATEGORY_FILTER = "CATEGORY_FILTER";
const PRICE_FILTER = "PRICE_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";
const SORT_PRICE_ASC_FILTER = "SORT_PRICE_ASC_FILTER";
const UPDATE_USER_DATA = "UPDATE_USER_DATA";
const UPDATE_TOKEN_AND_DATA = "UPDATE_TOKEN_AND_DATA";
const CREDENTIAL_CHECK = "CREDENTIAL_CHECK";
const USER_NOT_FOUND = "USER_NOT_FOUND";
const UPDATE_DEFAULT = "UPDATE_DEFAULT";
const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
const ADD_TO_CART = "ADD_TO_CART";
const MOVE_TO_SAVE_FOR_LATER = "MOVE_TO_SAVE_FOR_LATER";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const MOVE_TO_CART = "MOVE_TO_CART";
const INC_CART_COUNT = "INC_CART_COUNT";
const DEC_CART_COUNT = "DEC_CART_COUNT";
const UPDATE_SEARCH_TEXT = "UPDATE_SEARCH_TEXT";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";
const CLEAR_CART = "CLEAR_CART";
export {
  FILTER_CATEGORIES,
  RATING_FILTER,
  CATEGORY_FILTER,
  PRICE_FILTER,
  CLEAR_FILTER,
  SORT_PRICE_ASC_FILTER,
  UPDATE_USER_DATA,
  UPDATE_TOKEN_AND_DATA,
  CREDENTIAL_CHECK,
  USER_NOT_FOUND,
  UPDATE_DEFAULT,
  ADD_TO_WISHLIST,
  ADD_TO_CART,
  MOVE_TO_SAVE_FOR_LATER,
  REMOVE_FROM_CART,
  MOVE_TO_CART,
  INC_CART_COUNT,
  DEC_CART_COUNT,
  UPDATE_SEARCH_TEXT,
  CLEAR_CART,
  SEARCH_PRODUCT,
};
